### ISSUE TITLE
[Bug] /missing command can be used in "64x-submit-textures" and "32x-submit-textures"

### ISSUE THREAD

**Issue by HARYA301** [Faithful-Resource-Pack/CompliBot#255]
### What happened?

If you use /missing command in one of the submissons channels., the bot message and .txt file won't be deleted.
I can't confirm with any other / commands as of right now.

### To reproduce

1. Use a / command in one of the submissons channels.
2. The message won't be deleted.

### Screenshot(s)

![image](https://github.com/Faithful-Resource-Pack/CompliBot/assets/57374230/81d8e4ef-9bcd-4516-8bf6-c1c2ed825126)

**Comment by 3vorp** [comment]
probably a problem with slashCommandUsed, should filter out submission channels first and ephemerally warn user that they can't use commands in that channel

**Comment by 3vorp** [comment]
will be added once v4 is done (pretty soon hopefully)

**Comment by 3vorp** [comment]
<img width="1130" alt="Screen Shot 2023-10-13 at 10 32 00 PM" src="https://github.com/Faithful-Resource-Pack/CompliBot/assets/75297863/96efee7b-ac59-46fb-8840-3d6add5f1c75">

also turns out you can just add your own channel overrides which is arguably a better solution, so now there's both of them lol
